# Use the latest Ubuntu image
FROM ollama/ollama:latest

# Start Ollama serve in background, and pull model
# EXPOSE 11434
# RUN ollama --version
RUN apt update && apt install -y pip && rm -rf /var/lib/apt/lists/*
# RUN apt install -y pip && rm -rf /var/lib/apt/lists/*
RUN ollama serve & \
    sleep 10 && \
    ollama pull qwen2.5:0.5b
    
WORKDIR /usr/src/app
COPY . .
# CMD ["python", "--version"]
RUN pip install -U pip
RUN pip install -r requirements.txt
CMD ["chainlit", "run", "app.py", "-w"]